# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CARE_ArimotoPotter_cpp <- function(X, A, R, Q) {
    invisible(.Call(`_rMGIG_CARE_ArimotoPotter_cpp`, X, A, R, Q))
}

rMGIG_cpp <- function(n, nu, phi, psi, df, maxit) {
    .Call(`_rMGIG_rMGIG_cpp`, n, nu, phi, psi, df, maxit)
}

mMGIG_cpp <- function(nu, phi, psi) {
    .Call(`_rMGIG_mMGIG_cpp`, nu, phi, psi)
}

